### PR TITLE
update to 1.19.2

### PR DESCRIPTION
**Pull request by btwonion**

### CODE REVIEW

**Comment by btwonion** [comment]
In this pr are all changes from 1.19 to 1.19.1

**Comment by mooziii** [comment]
Why did you remove the quillt mappings?

**Comment by btwonion** [comment]
> Why did you remove the quillt mappings?

cause of this: https://github.com/FabricMC/fabric-loom/issues/693

**Comment by mooziii** [comment]
they work fine for me (maybe because you use build.1? the newest one is .2)

**Comment by btwonion** [comment]
Oh i see. I will change it later. I guess the version was released after I changed the library versions.

**Comment by btwonion** [comment]
ready to push for 1.19.2

**Comment by jakobkmar** [comment]
huh?

**Pull request closed without merging**
